url: http://csinva.github.io
baseurl: ""

# Site Settings
title: Chandan Singh
description: "Let's do good with models"
keywords: "Machine Learning, Chandan Singh, Berkeley, Interpretability, Explainability"
collections:
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
 timeline_blurbs:
    name: timeline_blurbs
    output: true
markdown: kramdown
highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
